### ISSUE TITLE
Combine forces with tvthemes?

### ISSUE THREAD

**Issue by marius-mather** [MatthewBJane/theme_park#1]
Seeing your fun themes reminded me that https://github.com/Ryo-N7/tvthemes has a similar aim - given you've said you don't have time to maintain this as a separate package, maybe you could integrate your themes into tvthemes and have them maintained that way?

**Comment by MatthewBJane** [comment]
It's a good idea! I think there is a bit of a different vision but I like the idea of combining them! I will have to reach out to him at some point. Thanks!
