### ISSUE TITLE
Facet titles do not currently follow the theme

### ISSUE THREAD

**Issue by lukepilling** [MatthewBJane/theme_park#2]
Currently the facet titles look like:

![image](https://github.com/MatthewBJane/theme_park/assets/4245328/24b85e8e-912f-4f31-9067-5d695c3f2f5e)

If you add this to the theme:

```r
+ theme(
  strip.background = element_rect(fill = lighter_color_barbie, colour = border_color_barbie),
  strip.text = element_text(colour = text_color_barbie)
)
```

It will look much better:

![image](https://github.com/MatthewBJane/theme_park/assets/4245328/933f491d-c14a-4e29-9cfa-83a155cbcaf8)

See (https://github.com/lukepilling/theme_park/commit/a06974df717036c43b3d57185d3863ca9174d001)

**Comment by MatthewBJane** [comment]
Excellent find! I will add these to each of the scripts. Thank you
