### ISSUE TITLE
barbie_font = FALSE

### ISSUE THREAD

**Issue by ASKurz** [MatthewBJane/theme_park#27]
I just downloaded **ThemePark** this afternoon (version 0.0.0.9000). When I use `theme_barbie()`with `barbie_font = FALSE`, it works, but I get a very long repeating warning. Here's a quick example code:

```{r}
library(tidyverse)
library(ThemePark)

mtcars %>% 
  ggplot(aes(mpg, wt)) +
  geom_point() +
  theme_barbie(barbie_font = FALSE) 
```
<img width="740" alt="Screenshot 2023-08-13 at 4 53 11 PM" src="https://github.com/MatthewBJane/theme_park/assets/19917004/062eb1c4-80c9-407b-9f8c-9869c0c7d5c7">

The warning, which I'll not show in full here, is a long repeating block of the following:

```
Warning: font family 'Arial' not found, will use 'sans' instead
```

**Comment by ASKurz** [comment]
As a side comment, I generally find `theme_barbie(barbie_font = TRUE)` delightful, but it doesn't work great when you want to use Greek symbols in your titles.

**Comment by MatthewBJane** [comment]
Hey Solomon, 
For the first comment:  yeah the default font should be 'sans' not 'Arial' so I will make that change for all the themes. Thanks for pointing that out. 
For the Second comment: Honestly, I am not sure how to solve this issue, @christopherkenny or @lukepilling may have some ideas.

**Comment by MatthewBJane** [comment]
Follow up: First comment has been resolved. When `name_theme(name_font=FALSE)` the font is now 'sans' for all themes.

**Comment by ASKurz** [comment]
Woot!
