### ISSUE TITLE
README changes

### ISSUE THREAD

**Issue by MatthewBJane** [MatthewBJane/theme_park#28]
1. We should probably make the figures in the README higher resolution
2. Add @lukepilling and @christopherkenny to the author list in BibTeX and APA citations
3. Since the Barbie theme got the most attention, it would be best to include Barbie as one of the example themes

**Comment by lukepilling** [comment]
Away from office at the mo but having Barbie theme as the main example makes a lot of sense to me!

**Comment by christopherkenny** [comment]
Yeah, I agree there. Just added these updates in PR #30, while taking a break from spinning my wheels on a different project. Can adjust the PR if you want it implemented differently.
