### ISSUE TITLE
Replacement font for Lugrasimo in `theme_lordoftherings`

### ISSUE THREAD

**Issue by christopherkenny** [MatthewBJane/theme_park#34]
For some reason, [Lugrasimo](https://fonts.google.com/specimen/Lugrasimo) does not seem to be supported by `sysfonts`. Seems like the best option is to find a similar calligraphic font.

**Comment by lukepilling** [comment]
Either of these might do the job?
https://fonts.google.com/specimen/Cinzel+Decorative
https://fonts.google.com/specimen/MedievalSharp

**Comment by christopherkenny** [comment]
MedievalSharp looks a little closer to the original to me, so I tried that. Seems to have fixed the issue.
